function snapshot = emptyTelemetrySnapshot()
%EMPTYTELEMETRYSNAPSHOT Create a typed, empty live telemetry snapshot.

snapshot = struct();
snapshot.schemaVersion = "1.1.0";
snapshot.revision = uint64(0);
snapshot.receivedUnixSec = NaN;
snapshot.systemId = NaN;
snapshot.componentId = NaN;
snapshot.sourceType = "waiting";

snapshot.data = struct( ...
    "Armed", NaN, ...
    "FlightMode", "", ...
    "SystemStatus", NaN, ...
    "Roll_rad", NaN, ...
    "Pitch_rad", NaN, ...
    "Yaw_rad", NaN, ...
    "P_radps", NaN, ...
    "Q_radps", NaN, ...
    "R_radps", NaN, ...
    "North_m", NaN, ...
    "East_m", NaN, ...
    "Down_m", NaN, ...
    "VNorth_mps", NaN, ...
    "VEast_mps", NaN, ...
    "VDown_mps", NaN, ...
    "X_m", NaN, ...
    "Y_m", NaN, ...
    "Z_m", NaN, ...
    "BatteryVoltage_V", NaN, ...
    "BatteryCurrent_A", NaN, ...
    "BatteryRemaining_pct", NaN, ...
    "BatteryConsumed_Ah", NaN, ...
    "GpsFixType", NaN, ...
    "GpsSatellites", NaN, ...
    "GpsHdop", NaN, ...
    "GpsLatitude_deg", NaN, ...
    "GpsLongitude_deg", NaN, ...
    "GpsAltitude_m", NaN, ...
    "MotorOutputPort", NaN, ...
    "RollTarget_rad", NaN, ...
    "PitchTarget_rad", NaN, ...
    "YawTarget_rad", NaN, ...
    "ThrustTarget", NaN, ...
    "EstimatorWindNorth_mps", NaN, ...
    "EstimatorWindEast_mps", NaN);

for index = 1:16
    snapshot.data.(sprintf("Motor%d_output", index)) = NaN;
    snapshot.data.(sprintf("Motor%d_pwm_us", index)) = NaN;
end
for index = 1:4
    snapshot.data.(sprintf("Motor%d_rpm", index)) = NaN;
end

definitions = vectra.px4.telemetryDefinitions();
channels = struct();
for index = 1:numel(definitions)
    definition = definitions(index);
    channels.(definition.key) = struct( ...
        "label", definition.label, ...
        "messageName", definition.messageName, ...
        "required", definition.required, ...
        "provenance", definition.provenance, ...
        "freshnessSec", definition.freshnessSec, ...
        "state", "waiting", ...
        "lastReceivedUnixSec", NaN, ...
        "ageSec", NaN, ...
        "rateHz", 0, ...
        "count", uint64(0));
end
snapshot.channels = channels;
end
