classdef SimulatedTelemetrySource < handle
    %SIMULATEDTELEMETRYSOURCE Deterministic source for tests and GUI QA.

    properties
        MessageCallback = []
        StatusCallback = []
    end

    properties (SetAccess = private)
        Status (1,1) string = "disconnected"
        ElapsedSec (1,1) double = 0
    end

    properties (Access = private)
        TickTimer = []
        Sequence (1,1) double = 0
        TickCount (1,1) double = 0
        StartUnixSec (1,1) double = NaN
    end

    methods
        function connect(this)
            if this.Status ~= "disconnected"
                return;
            end
            this.ElapsedSec = 0;
            this.Sequence = 0;
            this.TickCount = 0;
            this.StartUnixSec = posixtime(datetime( ...
                "now", "TimeZone", "UTC"));
            this.TickTimer = timer( ...
                ExecutionMode="fixedRate", ...
                Period=0.05, ...
                BusyMode="drop", ...
                TimerFcn=@(~, ~)this.tick());
            start(this.TickTimer);
            this.setStatus("simulated", ...
                "Deterministic simulated telemetry is active");
        end

        function disconnect(this)
            if ~isempty(this.TickTimer)
                try
                    stop(this.TickTimer);
                    delete(this.TickTimer);
                catch
                end
                this.TickTimer = [];
            end
            this.setStatus("disconnected", "Simulated source stopped");
        end

        function delete(this)
            this.disconnect();
        end
    end

    methods (Access = private)
        function tick(this)
            this.TickCount = this.TickCount + 1;
            this.ElapsedSec = 0.05 * this.TickCount;
            t = this.ElapsedSec;

            this.emit("ATTITUDE", struct( ...
                "time_boot_ms", uint32(t * 1000), ...
                "roll", 0.08 * sin(0.7 * t), ...
                "pitch", 0.05 * sin(0.45 * t + 0.6), ...
                "yaw", mod(0.12 * t + pi, 2 * pi) - pi, ...
                "rollspeed", 0.056 * cos(0.7 * t), ...
                "pitchspeed", 0.0225 * cos(0.45 * t + 0.6), ...
                "yawspeed", 0.12));

            if mod(this.TickCount, 2) == 0
                this.emit("LOCAL_POSITION_NED", struct( ...
                    "time_boot_ms", uint32(t * 1000), ...
                    "x", 0.7 * sin(0.09 * t), ...
                    "y", 0.5 * cos(0.11 * t), ...
                    "z", -2.0 - 0.12 * sin(0.35 * t), ...
                    "vx", 0.063 * cos(0.09 * t), ...
                    "vy", -0.055 * sin(0.11 * t), ...
                    "vz", -0.042 * cos(0.35 * t)));
                actuator = nan(32, 1);
                actuator(1:4) = 0.52 + 0.04 * [ ...
                    sin(t); cos(t); -sin(t); -cos(t)];
                this.emit("ACTUATOR_OUTPUT_STATUS", struct( ...
                    "time_usec", uint64(t * 1e6), ...
                    "active", uint32(15), ...
                    "actuator", actuator));
            end

            if mod(this.TickCount, 4) == 0
                this.emit("ESC_TELEMETRY_1_TO_4", struct( ...
                    "rpm", uint16(5200 + 320 * [ ...
                        sin(t), cos(t), -sin(t), -cos(t)])));
            end

            if mod(this.TickCount, 10) == 0
                voltageMv = uint16(max(13000, 16750 - 2.5 * t));
                this.emit("BATTERY_STATUS", struct( ...
                    "voltages", [voltageMv; repmat(uint16(65535), 9, 1)], ...
                    "current_battery", int16(1840 + 120 * sin(t)), ...
                    "current_consumed", int32(350 + 5 * t), ...
                    "battery_remaining", int8(max(0, 93 - floor(t / 12)))));
            end

            if mod(this.TickCount, 20) == 0
                this.emit("HEARTBEAT", struct( ...
                    "custom_mode", uint32(458752), ...
                    "type", uint8(2), ...
                    "autopilot", uint8(12), ...
                    "base_mode", uint8(128), ...
                    "system_status", uint8(4), ...
                    "mavlink_version", uint8(3)));
                this.emit("GPS_RAW_INT", struct( ...
                    "time_usec", uint64(t * 1e6), ...
                    "fix_type", uint8(3), ...
                    "lat", int32(373419000), ...
                    "lon", int32(1267321000), ...
                    "alt", int32(118000), ...
                    "eph", uint16(82), ...
                    "satellites_visible", uint8(17)));
            end
        end

        function emit(this, name, payload)
            this.Sequence = mod(this.Sequence + 1, 256);
            event = vectra.px4.makeTelemetryEvent(name, payload, ...
                SystemID=1, ...
                ComponentID=1, ...
                Sequence=this.Sequence, ...
                ReceivedUnixSec=this.StartUnixSec + this.ElapsedSec, ...
                SourceType="simulated");
            if ~isempty(this.MessageCallback)
                this.MessageCallback(event);
            end
        end

        function setStatus(this, state, detail)
            this.Status = string(state);
            if ~isempty(this.StatusCallback)
                this.StatusCallback(struct( ...
                    "state", string(state), ...
                    "detail", string(detail), ...
                    "unixSec", posixtime(datetime( ...
                        "now", "TimeZone", "UTC"))));
            end
        end
    end
end
