function definitions = telemetryDefinitions()
%TELEMETRYDEFINITIONS Define supported live PX4 MAVLink channels.

definitions = struct( ...
    "messageName", { ...
        "HEARTBEAT", ...
        "ATTITUDE", ...
        "LOCAL_POSITION_NED", ...
        "BATTERY_STATUS", ...
        "ACTUATOR_OUTPUT_STATUS", ...
        "GPS_RAW_INT", ...
        "ESC_TELEMETRY_1_TO_4", ...
        "ATTITUDE_TARGET", ...
        "WIND_COV"}, ...
    "key", { ...
        "heartbeat", ...
        "attitude", ...
        "localPosition", ...
        "battery", ...
        "actuators", ...
        "gps", ...
        "escRpm", ...
        "attitudeTarget", ...
        "estimatorWind"}, ...
    "label", { ...
        "PX4 heartbeat", ...
        "Attitude & rates", ...
        "Local position", ...
        "Battery", ...
        "Motor outputs", ...
        "GPS health", ...
        "Measured ESC RPM", ...
        "Attitude target", ...
        "Estimator wind"}, ...
    "required", {true, true, true, true, true, false, false, false, false}, ...
    "freshnessSec", {2.5, 0.5, 1.0, 3.0, 1.0, 3.0, 2.0, 1.0, 3.0}, ...
    "provenance", { ...
        "measured", "estimated", "estimated", "measured", "commanded", ...
        "measured", "measured", "commanded", "estimated"});
end
