classdef TestPX4Telemetry < matlab.unittest.TestCase
    methods (Test)
        function locksToHeartbeatAndNormalizesRequiredChannels(testCase)
            monitor = vectra.px4.TelemetryMonitor();
            baseTime = 1000;

            ignored = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE", attitudePayload(), ...
                ReceivedUnixSec=baseTime);
            testCase.verifyFalse(monitor.ingest(ignored));

            heartbeat = vectra.px4.makeTelemetryEvent( ...
                "HEARTBEAT", struct( ...
                    "type", uint8(2), ...
                    "autopilot", uint8(12), ...
                    "base_mode", uint8(128), ...
                    "custom_mode", uint32(7), ...
                    "system_status", uint8(4)), ...
                SystemID=3, ComponentID=1, ...
                Sequence=10, ReceivedUnixSec=baseTime + 0.1);
            testCase.verifyTrue(monitor.ingest(heartbeat));

            attitude = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE", attitudePayload(), ...
                SystemID=3, ComponentID=1, ...
                Sequence=11, ReceivedUnixSec=baseTime + 0.2);
            position = vectra.px4.makeTelemetryEvent( ...
                "LOCAL_POSITION_NED", struct( ...
                    "x", 1.2, "y", -0.4, "z", -2.5, ...
                    "vx", 0.3, "vy", 0.1, "vz", -0.2), ...
                SystemID=3, ComponentID=1, ...
                Sequence=12, ReceivedUnixSec=baseTime + 0.3);
            monitor.ingest(attitude);
            monitor.ingest(position);

            snapshot = monitor.Snapshot;
            testCase.verifyTrue(snapshot.data.Armed);
            testCase.verifyEqual(snapshot.data.Roll_rad, 0.1);
            testCase.verifyEqual(snapshot.data.P_radps, 0.4);
            testCase.verifyEqual(snapshot.data.North_m, 1.2);
            testCase.verifyEqual(snapshot.data.Z_m, 2.5);
            testCase.verifyEqual(snapshot.channels.attitude.state, "live");
            testCase.verifyEqual(monitor.LockedSystemID, 3);
        end

        function ignoresQgcHeartbeatBeforePx4Vehicle(testCase)
            monitor = vectra.px4.TelemetryMonitor();

            qgcHeartbeat = vectra.px4.makeTelemetryEvent( ...
                "HEARTBEAT", struct( ...
                    "type", uint8(6), ...
                    "autopilot", uint8(8), ...
                    "base_mode", uint8(0), ...
                    "custom_mode", uint32(0), ...
                    "system_status", uint8(4)), ...
                SystemID=255, ComponentID=190, ...
                Sequence=1, ReceivedUnixSec=1100);
            testCase.verifyFalse(monitor.ingest(qgcHeartbeat));
            testCase.verifyTrue(isnan(monitor.LockedSystemID));
            testCase.verifyEqual( ...
                monitor.RejectedLockHeartbeats, uint64(1));
            testCase.verifyEqual(monitor.ForeignMessages, uint64(0));

            px4Heartbeat = vectra.px4.makeTelemetryEvent( ...
                "HEARTBEAT", struct( ...
                    "type", uint8(2), ...
                    "autopilot", uint8(12), ...
                    "base_mode", uint8(128), ...
                    "custom_mode", uint32(0), ...
                    "system_status", uint8(4)), ...
                SystemID=1, ComponentID=1, ...
                Sequence=10, ReceivedUnixSec=1100.1);
            attitude = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE", attitudePayload(), ...
                SystemID=1, ComponentID=1, ...
                Sequence=11, ReceivedUnixSec=1100.2);
            position = vectra.px4.makeTelemetryEvent( ...
                "LOCAL_POSITION_NED", struct( ...
                    "x", 1.0, "y", 2.0, "z", -3.0, ...
                    "vx", 0.1, "vy", 0.2, "vz", -0.3), ...
                SystemID=1, ComponentID=1, ...
                Sequence=12, ReceivedUnixSec=1100.3);
            battery = vectra.px4.makeTelemetryEvent( ...
                "BATTERY_STATUS", struct( ...
                    "voltages", uint16([4200; 4200; 4200]), ...
                    "current_battery", int16(1000), ...
                    "current_consumed", int32(50), ...
                    "battery_remaining", int8(90)), ...
                SystemID=1, ComponentID=1, ...
                Sequence=13, ReceivedUnixSec=1100.4);

            testCase.verifyTrue(monitor.ingest(px4Heartbeat));
            testCase.verifyTrue(monitor.ingest(attitude));
            testCase.verifyTrue(monitor.ingest(position));
            testCase.verifyTrue(monitor.ingest(battery));
            testCase.verifyEqual(monitor.LockedSystemID, 1);
            testCase.verifyEqual(monitor.LockedComponentID, 1);
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.heartbeat.state, "live");
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.attitude.state, "live");
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.localPosition.state, "live");
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.battery.state, "live");
            testCase.verifyEqual( ...
                monitor.summary().rejectedLockHeartbeats, uint64(1));
        end

        function convertsBatteryUnitsAndUnknownSentinels(testCase)
            snapshot = vectra.px4.emptyTelemetrySnapshot();
            event = vectra.px4.makeTelemetryEvent( ...
                "BATTERY_STATUS", struct( ...
                    "voltages", uint16([4200; 4190; 4180; 65535]), ...
                    "current_battery", int16(1234), ...
                    "current_consumed", int32(-1), ...
                    "battery_remaining", int8(-1)), ...
                ReceivedUnixSec=2000);

            snapshot = vectra.px4.normalizeTelemetryMessage( ...
                snapshot, event);
            testCase.verifyEqual(snapshot.data.BatteryVoltage_V, ...
                12.57, "AbsTol", 1e-12);
            testCase.verifyEqual(snapshot.data.BatteryCurrent_A, ...
                12.34, "AbsTol", 1e-12);
            testCase.verifyTrue(isnan( ...
                snapshot.data.BatteryConsumed_Ah));
            testCase.verifyTrue(isnan( ...
                snapshot.data.BatteryRemaining_pct));
        end

        function rejectsForeignSystemAndCountsSequenceGap(testCase)
            monitor = vectra.px4.TelemetryMonitor();
            heartbeat = vectra.px4.makeTelemetryEvent( ...
                "HEARTBEAT", struct( ...
                    "type", uint8(2), ...
                    "autopilot", uint8(12), ...
                    "base_mode", uint8(0), ...
                    "custom_mode", uint32(0), ...
                    "system_status", uint8(3)), ...
                SystemID=1, Sequence=20, ReceivedUnixSec=3000);
            monitor.ingest(heartbeat);

            foreign = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE", attitudePayload(), ...
                SystemID=2, Sequence=21, ReceivedUnixSec=3000.1);
            testCase.verifyFalse(monitor.ingest(foreign));

            gapEvent = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE", attitudePayload(), ...
                SystemID=1, Sequence=23, ReceivedUnixSec=3000.2);
            monitor.ingest(gapEvent);

            testCase.verifyEqual(monitor.ForeignMessages, uint64(1));
            testCase.verifyEqual(monitor.SequenceGaps, uint64(2));
        end

        function marksLateChannelsStale(testCase)
            monitor = vectra.px4.TelemetryMonitor();
            event = vectra.px4.makeTelemetryEvent( ...
                "HEARTBEAT", struct( ...
                    "type", uint8(2), ...
                    "autopilot", uint8(12), ...
                    "base_mode", uint8(0), ...
                    "custom_mode", uint32(0), ...
                    "system_status", uint8(3)), ...
                ReceivedUnixSec=4000);
            monitor.ingest(event);
            monitor.refreshFreshness(4003);
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.heartbeat.state, "stale");
            testCase.verifyEqual( ...
                monitor.Snapshot.channels.attitude.state, "waiting");
        end

        function transformsAttitudeTargetQuaternion(testCase)
            snapshot = vectra.px4.emptyTelemetrySnapshot();
            halfAngle = deg2rad(30) / 2;
            event = vectra.px4.makeTelemetryEvent( ...
                "ATTITUDE_TARGET", struct( ...
                    "q", [cos(halfAngle), 0, 0, sin(halfAngle)], ...
                    "thrust", 0.55), ...
                ReceivedUnixSec=5000);
            snapshot = vectra.px4.normalizeTelemetryMessage( ...
                snapshot, event);
            testCase.verifyEqual(rad2deg( ...
                snapshot.data.YawTarget_rad), 30, ...
                "AbsTol", 1e-10);
            testCase.verifyEqual(snapshot.data.ThrustTarget, 0.55);
        end

        function acceptsServoOutputRawAsPwmFallback(testCase)
            snapshot = vectra.px4.emptyTelemetrySnapshot();
            event = vectra.px4.makeTelemetryEvent( ...
                "SERVO_OUTPUT_RAW", struct( ...
                    "port", uint8(0), ...
                    "servo1_raw", uint16(1000), ...
                    "servo2_raw", uint16(1250), ...
                    "servo3_raw", uint16(0), ...
                    "servo4_raw", uint16(65535)), ...
                ReceivedUnixSec=5500);

            snapshot = vectra.px4.normalizeTelemetryMessage( ...
                snapshot, event);

            testCase.verifyEqual(snapshot.data.MotorOutputPort, 0);
            testCase.verifyEqual(snapshot.data.Motor1_pwm_us, 1000);
            testCase.verifyEqual(snapshot.data.Motor2_pwm_us, 1250);
            testCase.verifyTrue(isnan(snapshot.data.Motor3_pwm_us));
            testCase.verifyTrue(isnan(snapshot.data.Motor4_pwm_us));
            testCase.verifyTrue(isnan(snapshot.data.Motor1_output));
            testCase.verifyEqual( ...
                snapshot.channels.actuators.messageName, ...
                "SERVO_OUTPUT_RAW");
            testCase.verifyEqual( ...
                snapshot.channels.actuators.state, "live");
        end

        function preservesNormalizedActuatorOutput(testCase)
            snapshot = vectra.px4.emptyTelemetrySnapshot();
            event = vectra.px4.makeTelemetryEvent( ...
                "ACTUATOR_OUTPUT_STATUS", struct( ...
                    "active", uint32(15), ...
                    "actuator", [0.2; 0.3; 0.4; 0.5]), ...
                ReceivedUnixSec=5600);

            snapshot = vectra.px4.normalizeTelemetryMessage( ...
                snapshot, event);

            testCase.verifyEqual(snapshot.data.Motor1_output, 0.2);
            testCase.verifyEqual(snapshot.data.Motor4_output, 0.5);
            testCase.verifyTrue(isnan(snapshot.data.Motor1_pwm_us));
            testCase.verifyEqual( ...
                snapshot.channels.actuators.messageName, ...
                "ACTUATOR_OUTPUT_STATUS");
        end

        function reportsPassiveHardwarePrerequisites(testCase)
            report = vectra.px4.checkTelemetryHardware(14662);
            testCase.verifyEqual(report.localPort, 14662);
            testCase.verifyTrue(report.localPortAvailable);
            testCase.verifyClass(report.usbSerialPorts, "string");
            testCase.verifyClass(report.ready, "logical");
        end
    end
end

function payload = attitudePayload()
payload = struct( ...
    "roll", 0.1, ...
    "pitch", -0.2, ...
    "yaw", 0.3, ...
    "rollspeed", 0.4, ...
    "pitchspeed", -0.5, ...
    "yawspeed", 0.6);
end
