classdef TestAnalysis < matlab.unittest.TestCase
    methods (Test)
        function calculatesKnownTrackingMetrics(testCase)
            time = seconds((0:0.1:1)');
            count = numel(time);
            zero = zeros(count, 1);
            oneDegree = deg2rad(ones(count, 1));
            data = timetable(time, oneDegree, zero, zero, ...
                zero, zero, zero, zero, zero, zero, ...
                'VariableNames', { ...
                'Roll_rad', 'Pitch_rad', 'Yaw_rad', ...
                'RollCmd_rad', 'PitchCmd_rad', 'YawCmd_rad', ...
                'X_m', 'Y_m', 'Z_m'});

            metrics = vectra.analysis.calculateMetrics(data);
            testCase.verifyEqual(metrics.rollTrackingRmseDeg, 1, ...
                "AbsTol", 1e-10);
            testCase.verifyEqual(metrics.positionHoldRmseM, 0, ...
                "AbsTol", eps);
        end
    end
end
