classdef TestLiveTelemetryLogger < matlab.unittest.TestCase
    properties
        TemporaryRoot
    end

    methods (TestMethodSetup)
        function createTemporaryRoot(testCase)
            testCase.TemporaryRoot = string(tempname);
            mkdir(testCase.TemporaryRoot);
        end
    end

    methods (TestMethodTeardown)
        function removeTemporaryRoot(testCase)
            if isfolder(testCase.TemporaryRoot)
                rmdir(testCase.TemporaryRoot, "s");
            end
        end
    end

    methods (Test)
        function writesJournalSamplesAndManifest(testCase)
            resolved = minimalResolved("logger-test-001");
            logger = vectra.data.LiveTelemetryLogger( ...
                resolved, RootDirectory=testCase.TemporaryRoot, ...
                SamplePeriodSec=0.1);
            monitor = vectra.px4.TelemetryMonitor();

            events = [
                vectra.px4.makeTelemetryEvent( ...
                    "HEARTBEAT", struct( ...
                        "type", uint8(2), ...
                        "autopilot", uint8(12), ...
                        "base_mode", uint8(0), ...
                        "custom_mode", uint32(0), ...
                        "system_status", uint8(3)), ...
                    Sequence=1, ReceivedUnixSec=100)
                vectra.px4.makeTelemetryEvent( ...
                    "ATTITUDE", struct( ...
                        "roll", 0.1, "pitch", 0.2, "yaw", 0.3, ...
                        "rollspeed", 0.4, "pitchspeed", 0.5, ...
                        "yawspeed", 0.6), ...
                    Sequence=2, ReceivedUnixSec=100.2)
                vectra.px4.makeTelemetryEvent( ...
                    "SERVO_OUTPUT_RAW", struct( ...
                        "port", uint8(0), ...
                        "servo1_raw", uint16(1000), ...
                        "servo2_raw", uint16(1010), ...
                        "servo3_raw", uint16(1020), ...
                        "servo4_raw", uint16(1030)), ...
                    Sequence=3, ReceivedUnixSec=100.4)
            ];

            for index = 1:numel(events)
                monitor.ingest(events(index));
                logger.append(events(index), monitor.Snapshot);
            end
            logger.stop("unit-test", ...
                monitor.summary(), monitor.channelStatus());

            runDirectory = fullfile( ...
                testCase.TemporaryRoot, resolved.runId);
            testCase.verifyTrue(isfile(fullfile( ...
                runDirectory, "resolved_config.json")));
            testCase.verifyTrue(isfile(fullfile( ...
                runDirectory, "telemetry_events.jsonl")));
            testCase.verifyTrue(isfile(fullfile( ...
                runDirectory, "telemetry_samples.csv")));
            testCase.verifyTrue(isfile(fullfile( ...
                runDirectory, "telemetry_manifest.json")));

            journalLines = splitlines(strtrim(fileread(fullfile( ...
                runDirectory, "telemetry_events.jsonl"))));
            testCase.verifyNumElements(journalLines, 3);
            samples = readtable(fullfile( ...
                runDirectory, "telemetry_samples.csv"), ...
                VariableNamingRule="preserve");
            testCase.verifyTrue(ismember( ...
                "Motor1_pwm_us", string(samples.Properties.VariableNames)));
            testCase.verifyEqual(samples.Motor1_pwm_us(end), 1000);
            testCase.verifyEqual(samples.Motor4_pwm_us(end), 1030);
            testCase.verifyEqual(samples.MotorOutputPort(end), 0);
            manifest = jsondecode(fileread(fullfile( ...
                runDirectory, "telemetry_manifest.json")));
            testCase.verifyEqual( ...
                string(manifest.schemaVersion), "1.1.0");
            testCase.verifyEqual(manifest.eventCount, 3);
            testCase.verifyEqual(string(manifest.stopReason), "unit-test");
        end

        function recoversManifestWithoutChangingJournal(testCase)
            runDirectory = fullfile( ...
                testCase.TemporaryRoot, "recovery-test");
            mkdir(runDirectory);
            journalFile = fullfile( ...
                runDirectory, "telemetry_events.jsonl");
            events = [
                vectra.px4.makeTelemetryEvent( ...
                    "HEARTBEAT", struct(), ...
                    Sequence=1, ReceivedUnixSec=10)
                vectra.px4.makeTelemetryEvent( ...
                    "ATTITUDE", struct(), ...
                    Sequence=2, ReceivedUnixSec=12)
            ];
            fileId = fopen(journalFile, "w", "n", "UTF-8");
            cleanup = onCleanup(@() fclose(fileId));
            for index = 1:numel(events)
                fprintf(fileId, "%s\n", jsonencode(events(index)));
            end
            clear cleanup;
            before = fileread(journalFile);

            manifestFile = ...
                vectra.data.recoverTelemetryManifest(runDirectory);

            testCase.verifyEqual(fileread(journalFile), before);
            manifest = jsondecode(fileread(manifestFile));
            testCase.verifyTrue(manifest.recovered);
            testCase.verifyEqual(manifest.eventCount, 2);
            testCase.verifyEqual(manifest.durationSec, 2);
        end

        function refusesToOverwriteExistingRun(testCase)
            resolved = minimalResolved("existing-run");
            mkdir(fullfile(testCase.TemporaryRoot, resolved.runId));
            testCase.verifyError(@() ...
                vectra.data.LiveTelemetryLogger( ...
                    resolved, RootDirectory=testCase.TemporaryRoot), ...
                "vectra:data:RunAlreadyExists");
        end
    end
end

function resolved = minimalResolved(runId)
resolved = struct( ...
    "schemaVersion", "1.0.0", ...
    "runId", runId, ...
    "createdAt", "2026-07-27T00:00:00.000Z", ...
    "source", "simulation", ...
    "vehicle", struct(), ...
    "geometry", struct(), ...
    "experiment", struct(), ...
    "software", struct(), ...
    "hardware", struct());
end
